// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu7kejrmFn1BKdRM4dNJGfTzjT8nq1XHc',
    appId: '1:738847169464:web:0b65d776ea06b17bde4d4d',
    messagingSenderId: '738847169464',
    projectId: 'pothole-detection-abe46',
    authDomain: 'pothole-detection-abe46.firebaseapp.com',
    storageBucket: 'pothole-detection-abe46.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4-6wZCHdDweYmJajdu7wa5aIAnka9cBI',
    appId: '1:738847169464:android:94e61ba4c15f60dcde4d4d',
    messagingSenderId: '738847169464',
    projectId: 'pothole-detection-abe46',
    storageBucket: 'pothole-detection-abe46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbjnrZ9W2_Qg97W8RUKciytRU_U599c1w',
    appId: '1:738847169464:ios:08ba80ff1744afe2de4d4d',
    messagingSenderId: '738847169464',
    projectId: 'pothole-detection-abe46',
    storageBucket: 'pothole-detection-abe46.firebasestorage.app',
    iosClientId: '738847169464-9sr613v0dt9aaribj550sf1la6ln4ore.apps.googleusercontent.com',
    iosBundleId: 'com.example.pothole1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbjnrZ9W2_Qg97W8RUKciytRU_U599c1w',
    appId: '1:738847169464:ios:08ba80ff1744afe2de4d4d',
    messagingSenderId: '738847169464',
    projectId: 'pothole-detection-abe46',
    storageBucket: 'pothole-detection-abe46.firebasestorage.app',
    iosClientId: '738847169464-9sr613v0dt9aaribj550sf1la6ln4ore.apps.googleusercontent.com',
    iosBundleId: 'com.example.pothole1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu7kejrmFn1BKdRM4dNJGfTzjT8nq1XHc',
    appId: '1:738847169464:web:1da58b5d1713fa27de4d4d',
    messagingSenderId: '738847169464',
    projectId: 'pothole-detection-abe46',
    authDomain: 'pothole-detection-abe46.firebaseapp.com',
    storageBucket: 'pothole-detection-abe46.firebasestorage.app',
  );

}